[[repos]]
repo = "builtin"
hooks = [
    { id = "check-json" },
    { id = "check-yaml" },
    { id = "check-toml" },
    { id = "check-merge-conflict" },
    { id = "end-of-file-fixer" },
    { id = "fix-byte-order-marker" },
    { id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.0"
hooks = [
    { id = "ruff-check", args = ["--fix"] },
    { id = "ruff-format" },
]
