# Generated by Django 5.0.3 on 2024-03-20 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('budget_goal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voter_count', models.IntegerField()),
                ('total_count', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VotingRound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round_number', models.IntegerField()),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.voting')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('member_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voting_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.votinground')),
            ],
            options={
                'unique_together': {('voting_round', 'member_id')},
            },
        ),
    ]
