# Generated by Django 5.0.3 on 2024-03-21 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Voting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255, verbose_name="Bezeichnung")),
                (
                    "budget_goal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Ziel-Budget"
                    ),
                ),
                ("voter_count", models.IntegerField(verbose_name="Teilnehmeranzahl")),
                ("total_count", models.IntegerField(verbose_name="Mitgliederanzahl")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-datetime"],
            },
        ),
        migrations.CreateModel(
            name="VotingRound",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("round_number", models.IntegerField(verbose_name="Runde")),
                ("active", models.BooleanField(verbose_name="Aktiv")),
                (
                    "voting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="voting.voting",
                    ),
                ),
            ],
            options={
                "ordering": ["voting", "round_number"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("member_id", models.IntegerField(verbose_name="Mitgliedsnummer")),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Beitrag"),
                ),
                (
                    "voting_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="voting.votinground",
                    ),
                ),
            ],
            options={
                "ordering": ["member_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="votinground",
            constraint=models.UniqueConstraint(
                fields=("voting", "round_number"), name="unique_round_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="votinground",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("voting", "active"),
                name="unique_active_round",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("voting_round", "member_id")},
        ),
    ]
