# Generated by Django 5.0.3 on 2024-04-03 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="votinground",
            name="bids_applied",
            field=models.BooleanField(default=False, verbose_name="Gebote angewendet"),
        ),
        migrations.AlterField(
            model_name="voting",
            name="total_count",
            field=models.IntegerField(
                help_text="Anzahl der Mitglieder insgesamt.", verbose_name="Mitgliederanzahl"
            ),
        ),
        migrations.AlterField(
            model_name="voting",
            name="voter_count",
            field=models.IntegerField(
                help_text="Anzahl der Teilnehmer vor Ort (inkl. im voraus abgegebener Gebote).",
                verbose_name="Teilnehmeranzahl",
            ),
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("round_number", models.IntegerField(verbose_name="Runde")),
                ("member_id", models.IntegerField(verbose_name="Mitgliedsnummer")),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Gebot"),
                ),
                (
                    "voting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="voting.voting",
                    ),
                ),
            ],
            options={
                "ordering": ["member_id"],
                "unique_together": {("member_id", "round_number")},
            },
        ),
    ]
