# Generated by Django 5.0.3 on 2024-03-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="votinground",
            name="active",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="votinground",
            constraint=models.UniqueConstraint(
                fields=("voting", "round_number"), name="unique_round_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="votinground",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("voting", "active"),
                name="unique_active_round",
            ),
        ),
    ]
