# Generated by Django 5.0.3 on 2024-03-20 18:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0002_votinground_active_votinground_unique_round_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vote",
            options={"ordering": ["member_id"]},
        ),
        migrations.AlterModelOptions(
            name="voting",
            options={"ordering": ["-datetime"]},
        ),
        migrations.AlterModelOptions(
            name="votinground",
            options={"ordering": ["voting", "round_number"]},
        ),
        migrations.AddField(
            model_name="voting",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="votinground",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vote",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Beitrag"),
        ),
        migrations.AlterField(
            model_name="vote",
            name="member_id",
            field=models.IntegerField(verbose_name="Mitgliedsnummer"),
        ),
        migrations.AlterField(
            model_name="voting",
            name="budget_goal",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Ziel-Budget"),
        ),
        migrations.AlterField(
            model_name="voting",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Bezeichnung"),
        ),
        migrations.AlterField(
            model_name="voting",
            name="total_count",
            field=models.IntegerField(verbose_name="Mitgliederanzahl"),
        ),
        migrations.AlterField(
            model_name="voting",
            name="voter_count",
            field=models.IntegerField(verbose_name="Teilnehmeranzahl"),
        ),
        migrations.AlterField(
            model_name="votinground",
            name="active",
            field=models.BooleanField(verbose_name="Aktiv"),
        ),
        migrations.AlterField(
            model_name="votinground",
            name="round_number",
            field=models.IntegerField(verbose_name="Runde"),
        ),
        migrations.AlterField(
            model_name="votinground",
            name="voting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rounds",
                to="voting.voting",
            ),
        ),
    ]
