# Generated by Django 5.0.3 on 2024-04-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0003_alter_bid_options_alter_vote_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="voting",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Bieterrunde",
                "verbose_name_plural": "Bieterrunden",
            },
        ),
        migrations.RenameField(
            model_name="voting",
            old_name="datetime",
            new_name="created_at",
        ),
    ]
