# Generated by Django 5.2.11 on 2026-04-05 15:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0004_alter_voting_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("member_id", models.IntegerField(unique=True, verbose_name="Mitgliedsnummer")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Wähler",
                "verbose_name_plural": "Wähler",
                "ordering": ["member_id"],
            },
        ),
        migrations.AlterModelOptions(
            name="bid",
            options={
                "ordering": ["voting", "member_id", "round_number"],
                "verbose_name": "Absenz-Gebot",
                "verbose_name_plural": "Absenz-Gebote",
            },
        ),
        migrations.RemoveField(
            model_name="voting",
            name="voter_count",
        ),
        migrations.AlterField(
            model_name="voting",
            name="total_count",
            field=models.PositiveIntegerField(
                help_text="Anzahl der Mitglieder insgesamt",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Mitgliederanzahl",
            ),
        ),
        migrations.CreateModel(
            name="VotingVoter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "absent_from_round",
                    models.IntegerField(
                        blank=True, default=None, null=True, verbose_name="Abwesend ab Runde"
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voting_voters",
                        to="voting.voter",
                    ),
                ),
                (
                    "voting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voting_voters",
                        to="voting.voting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teilnahme",
                "verbose_name_plural": "Teilnahmen",
                "ordering": ["voter__member_id"],
                "unique_together": {("voting", "voter")},
            },
        ),
        migrations.AddField(
            model_name="voting",
            name="voters",
            field=models.ManyToManyField(
                related_name="votings", through="voting.VotingVoter", to="voting.voter"
            ),
        ),
    ]
