# Generated by Django 5.2.11 on 2026-04-08 22:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_voter_alter_bid_options_remove_voting_voter_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Datum'),
            preserve_default=False,
        ),
    ]
