# Generated by Django 5.2.11 on 2026-04-16 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0006_voting_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="voter",
            options={
                "ordering": ["member_id"],
                "verbose_name": "Teilnehmer",
                "verbose_name_plural": "Teilnehmer",
            },
        ),
    ]
