# Generated by Django 5.2.11 on 2026-05-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0007_alter_voter_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voting",
            name="date",
            field=models.DateTimeField(verbose_name="Datum"),
        ),
    ]
